### ISSUE TITLE
Custom migration-table-name not supported?

### ISSUE THREAD

**Issue by marcjeanson** [luminus-framework/luminus-migrations#3]
I use migratus with a custom table name configured in project.clj like so:

:migratus {:store :database :migration-table-name "migratus" :db ~(get (System/getenv) "DATABASE_URL”)}

However, I don’t think it’s possible to use the custom table name with this command line wrapper, or perhaps I missed something?

Any help you can provide would be awesome. Thanks!

**Comment by yogthos** [comment]
Yeah, that's an omission on my part. I just released version `0.2.0` that takes a map as a second argument. The url should specified using the `:database-url` key. All the other options are the same as migratus ones. Let me know if this works for you.

**Comment by marcjeanson** [comment]
Works great! Thanks for fixing this so quickly!

**Comment by yogthos** [comment]
glad to hear everything's working 👍
