### ISSUE TITLE
"java.lang.String to clojure.lang.IPersistentMap" cast error when running "lein test"

### ISSUE THREAD

**Issue by javipeg** [luminus-framework/luminus-migrations#4]
While going over the guestbook example from the **"Web Development with Clojure, Second Edition"** book, running `lein test` triggers:

`Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to clojure.lang.IPersistentMap`

I'm using a fresh clojure + leiningen + luminus install with the latest revision of luminus and the related dependencies.

Switching the luminus-migrations version from **0.2.2** to **0.1.9** or lower, makes the problem go away. So, this seems to have somthing to do with commit cfd4481. 

Reverting the change at file `src/luminus_migrations/core.clj` in version **0.2.2** makes the error go away for me.

I didn't get this error when running `lein run migrate`.

Thanks!

**Comment by yogthos** [comment]
Hi,

The API had a slight change in it. The library now takes a map of options as an argument instead of a string. However, that should work with the latest Luminus version. The test fixture in the `<app>.test.db.core` namespace should look like this in the latest template:

``` clojure
(use-fixtures
  :once
  (fn [f]
    (mount/start
      #'myapp.config/env
      #'myapp.db.core/*db*)
    (migrations/migrate ["migrate"] (select-keys env [:database-url]))
    (f)))
```

The older templates passed the URL directly: `(migrations/migrate ["migrate"] (:database-url env))`.

**Comment by javipeg** [comment]
Ok. That makes sense. I should have realised 0.1.9 -> 0.2.0 meant an API breaking change. 

It's working now. Thanks!  I can go back to keep improving my clojure skills :-P

**Comment by yogthos** [comment]
👍
And thanks for reporting this, I've updated the book to match the latest template. Hopefully, will avoid confusion for others.
