### ISSUE TITLE
Different behavior between "lein migratus" and "java -jar project.jar init"

### ISSUE THREAD

**Issue by ILoveHubGit** [luminus-framework/luminus-migrations#7]
I'm working on a small application which uses an H2 database.
Recently I added a table with some DECIMAL(18,10) and DECIMAL(19,4) columns. Because there were more changes to the database and it is just a prototype I'm working on the data in the database is not important. Therefore the migration script I made for the database first dropped all existing tables and then creates every table from scratch.

I see the following behavior:

1. If I run "lein migratus" in my development environment a new empty database is created and I can start the application with "lein run"
2. If I use "lein uberjar" to create a jar file and test this in a test folder on th same PC "java -Dconf=config.edn -jar project.jar init" (database url in config.edn file) a database file (only the mv not the trace variant) is created, but the process stops with a java.lang.NullPointerException. See below

read config from resource: "config.edn"
read config from file: "config.edn"
Exception in thread "main" java.lang.NullPointerException: entry
	at java.util.zip.ZipFile.getInputStream(ZipFile.java:346)
	at java.util.jar.JarFile.getInputStream(JarFile.java:447)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at migratus.database$find_init_script_resource.invokeStatic(database.clj:105)
	at migratus.database$find_init_script_resource.invoke(database.clj:98)
	at migratus.database$find_init_script.invokeStatic(database.clj:112)
	at migratus.database$find_init_script.invoke(database.clj:107)
	at migratus.database$init_db_BANG_.invokeStatic(database.clj:180)
	at migratus.database$init_db_BANG_.invoke(database.clj:179)
	at migratus.database.Database.init(database.clj:194)
	at migratus.core$init.invokeStatic(core.clj:128)
	at migratus.core$init.doInvoke(core.clj:125)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at luminus_migrations.core$init.invokeStatic(core.clj:36)
	at luminus_migrations.core$init.invoke(core.clj:24)
	at project.core$_main.invokeStatic(core.clj:58)
	at project.core$_main.doInvoke(core.clj:53)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at project.core.main(Unknown Source)

However, if I take the database created in my development environment and copy this to the test environment I can run the application "java -Dconf=config.edn -jar project.jar" without any problem.

It looks to me that somehow the type DECIMAL caused the problem, because this was a new type I used in an extra table I added to my database.

**Comment by yogthos** [comment]
The exception seems to indicate that migratus is failing to locate the init script on the resource path. It's tracing back to [here](https://github.com/yogthos/migratus/blob/86f4d50e5713ae09abe08a0802185e3320032465/src/migratus/database.clj#L98). Check that the `:init-script` key in the config to see if it matches the init file.

**Comment by ILoveHubGit** [comment]
I read the discussion in [https://github.com/yogthos/migratus/issues/85] but I'm still not sure in what config to add :init-script. 

I'm not working directly with migratus, I use luminus-migrations so I've no direct references to migratus.
Therefore I renamed the sql script in the resource folder to init.sql and created an uberjar.
After this the command "java -Dconf=config.edn -jar project.jar init" successfully created a database and then I could start the application.

Can you tell me where I should add :init-script in my project?
Will I run into a similar problem if I want to migrate the database?

**Comment by yogthos** [comment]
There's an [init](https://github.com/luminus-framework/luminus-migrations/blob/master/src/luminus_migrations/core.clj#L24) function in luminus-migrations that should be passed the config. Looking at it now, it doesn't look like that's setup correctly out of the box though. In the `core` namespace for your app, where the `-main` is, there should be something like the following:

```clojure
(defn -main [& args]
  (cond
    (some #{"init"} args)
    (do
      (mount/start #'myapp.config/env)
      (migrations/init (select-keys env [:database-url]))
      (System/exit 0))
    (some #{"migrate" "rollback"} args)
    (do
      (mount/start #'myapp.config/env)
      (migrations/migrate args (select-keys env [:database-url]))
      (System/exit 0))
    :else
    (start-app args)))
```

So, when the app is started with the `init` arg it will attempt to run the init script. It looks like `(migrations/init (select-keys env [:database-url]))` should be `(migrations/init (select-keys env [:database-url init-script]))` though.

**Comment by ILoveHubGit** [comment]
I added ":init-script" to the line you indicated 
Renamed the script file back to its original name "20170729205900-new-db.up.sql"
Created a new uberjar file
Added :init-script "20170729205900-new-db.up.sql" to the config.edn file
And ran the command "java -Dconf=config.edn -jar project.jar init"

Now it successfully generates the database :-)
Thanks a lot

P.S.: This means I think that the Luminus template should be changed so :init-script is default available in the -main function. I see you already made the change :-)

**Comment by yogthos** [comment]
Fantastic, and thanks for the help tracking it down. 👍

**Comment by ILoveHubGit** [comment]
You're welcome

**Comment by temco** [comment]
> There's an [init](https://github.com/luminus-framework/luminus-migrations/blob/master/src/luminus_migrations/core.clj#L24) function in luminus-migrations that should be passed the config. Looking at it now, it doesn't look like that's setup correctly out of the box though. In the `core` namespace for your app, where the `-main` is, there should be something like the following:
> 
> ```clojure
> (defn -main [& args]
>   (cond
>     (some #{"init"} args)
>     (do
>       (mount/start #'myapp.config/env)
>       (migrations/init (select-keys env [:database-url]))
>       (System/exit 0))
>     (some #{"migrate" "rollback"} args)
>     (do
>       (mount/start #'myapp.config/env)
>       (migrations/migrate args (select-keys env [:database-url]))
>       (System/exit 0))
>     :else
>     (start-app args)))
> ```
> 
> So, when the app is started with the `init` arg it will attempt to run the init script. It looks like `(migrations/init (select-keys env [:database-url]))` should be `(migrations/init (select-keys env [:database-url init-script]))` though.

when `:init-script` isn't defined in the corresponding edn file, what's its default value?

**Comment by yogthos** [comment]
Yup, that was a bug. The latest template is actually [set up to pass `:init-script` key to `migrations/init`](https://github.com/luminus-framework/luminus-template/blob/0cc32d692a57a7fec97bbce4c8b75608f76d5b79/resources/leiningen/new/luminus/core/src/core.clj#L73).
